seo:
  site_name: Seafood On Parade
  title: Seafood On Parade, Norwood
  description: A local seafood company operating in Norwood for many years, Peter and Koula have a loyal customer base thanks to their friendly service and the freshness of the seafood. Whether it’s fish, oysters, prawns or lobster, you can be assured of the quality.
  keywords: 
  social_image: https://seafoodonparade.com.au/images/social-sharing.png
  social-image-alt: Fresh seafood on the Parade Norwood
  favicon_image: 
_comments:
  title: Max 70 characters
  social_image: Landscape 1200 x 627px (twitter 280px x 80px make sure okay to crop)
social:
  instagram_username:
  facebook_url:
  twitter_username:
design:
  dark_color: '#158981'
  darker_color: '#0f5c5d'
  blue_color: '#E7F8F7'
  featured-text_color: '#0e5c5d'
  orange_color: '#FA6107'
  grey_color: 'rgba(90,90,90)'
  orange-text_color: '#FA6107'
  lorange-text_color: '#fd8139'
  light-text_color: 'white'